<x-app-layout>
<x-slot name="header"><div style="max-width:980px;margin:auto;display:flex;justify-content:space-between;align-items:center"><div><a href="{{ route('operator-chat.supervisor.index') }}" style="font-size:10px;color:#2563eb">← Chat Operator</a><h2 style="font-weight:800;margin-top:4px">Kelola Operator PC</h2><p style="font-size:10px;color:#94a3b8">Buat user role PC Operator, lalu tempatkan ke armada dan nomor PC.</p></div>@if(Route::has('developer.users.create'))<a href="{{ route('developer.users.create') }}" style="padding:9px 12px;border-radius:9px;background:#2563eb;color:white;font-size:10px;text-decoration:none">+ Buat Akun Operator</a>@endif</div></x-slot>
<style>.aw{max-width:980px;margin:auto;padding:18px}.notice{padding:10px 12px;border:1px solid #bfdbfe;background:#eff6ff;color:#1e40af;border-radius:10px;font-size:10px;margin-bottom:12px}.dark .notice{background:#102442;color:#bfdbfe;border-color:#294a78}.card{border:1px solid #dbe3ed;border-radius:14px;overflow:hidden;background:white}.dark .card{background:#101c30;border-color:#2d405d}.row{display:grid;grid-template-columns:1fr 150px 90px 140px auto;gap:8px;align-items:center;padding:11px;border-bottom:1px solid #e8edf4}.dark .row{border-color:#263853}.u small{display:block;color:#94a3b8}.row input,.row select{width:100%;padding:8px;border:1px solid #94a3b8;border-radius:8px;background:transparent;color:inherit}.btn{border:0;border-radius:8px;background:#2563eb;color:#fff;padding:8px;font-size:9px}.del{background:#ef4444}@media(max-width:780px){.row{grid-template-columns:1fr 1fr}.u{grid-column:1/-1}}</style>
<div class="aw"><div class="notice">Role <b>PC Operator</b> dibatasi oleh middleware: hanya Chat + Catatan. URL SIMOLA lain akan diarahkan kembali ke portal operator.</div>@if(session('success'))<div class="notice">{{ session('success') }}</div>@endif @if(session('error'))<div class="notice">{{ session('error') }}</div>@endif<div class="card">
@forelse($operators as $o)@php($a=$assignments->get($o->id))
<form class="row" method="POST" action="{{ route('operator-chat.assignments.store') }}">@csrf<input type="hidden" name="user_id" value="{{ $o->id }}"><div class="u"><b>{{ $o->name }}</b><small>{{ $o->email }}</small></div><select name="fleet_type"><option value="MT_LPG" @selected(($a?->fleet_type??'MT_LPG')==='MT_LPG')>MT LPG</option><option value="MT_PERTASHOP" @selected($a?->fleet_type==='MT_PERTASHOP')>MT PERTASHOP</option></select><input type="number" name="pc_number" min="1" max="99" value="{{ $a?->pc_number??1 }}" required><input type="text" name="label" maxlength="100" value="{{ $a?->label }}" placeholder="Label opsional"><div style="display:flex;gap:5px"><button class="btn">Simpan</button>@if($a)<button type="submit" class="btn del" form="del-{{ $a->id }}">Lepas</button>@endif</div></form>@if($a)<form id="del-{{ $a->id }}" method="POST" action="{{ route('operator-chat.assignments.destroy',$a) }}">@csrf @method('DELETE')</form>@endif
@empty<div style="padding:36px;text-align:center;color:#94a3b8">Belum ada user dengan role PC Operator.</div>@endforelse
</div></div>
</x-app-layout>
